"""test migration

Revision ID: 566459be7ac6
Revises: 13be50d9bc05
Create Date: 2025-03-02 23:58:14.603474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566459be7ac6'
down_revision = '13be50d9bc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
